apps/client/app/(afterLogin)/my-study/_components/StudyCurriculum.tsx, apps/client/app/(afterLogin)/study-apply/_components/StudyItem.tsx, apps/client/constants/apiPath.ts, apps/client/types/dtos/myStudy.ts, apps/client/types/entities/common/study.ts, apps/client/types/entities/myStudy.ts
클라이언트 스터디 커리큘럼 api 엔드 포인트 및 dto 변경사항 반영했습니다!
- #73 
@eugene028 @hamo-o 내일 qa 전에 꼭 리뷰 부탁드립니다..
=> [Chore] 클라이언트 스터디 커리큘럼 api 엔드 포인트 및 dto 변경사항 반영

apps/client/app/(afterLogin)/study-apply/_components/StudyItem.tsx, apps/client/types/dtos/applyStudy.ts
- 과제 스터디의 경우 "-"를 렌더링합니다.
- #76
=> [Fix] 수강신청 페이지 과제 스터디의 경우

apps/client/app/(afterLogin)/my-study/_components/StudyCurriculum.tsx, apps/client/middleware.ts
나의 스터디 페이지 스터디 커리큘럼 반응형 디자인 적용했습니다.
- #97
=> [Design] 나의 스터디 페이지 스터디 커리큘럼 반응형 디자인 적용

apps/client/apis/studyApplyApi.ts, apps/client/app/(afterLogin)/my-study/my-assignment/_components/AssignmentContent/AssignmentOverviewBox/FailurePopover.tsx, apps/client/app/(afterLogin)/my-study/my-assignment/_components/AssignmentDescription.tsx, apps/client/app/(afterLogin)/study-apply/_components/StudyItem.tsx, apps/client/constants/revalidateTime.ts, apps/client/types/entities/common/study.ts
- api 응답이 커리큘럼 -> 스터디로 바뀌어서 이 부분 반영합니다. (태그 이상하게 보이는 곳도 여기서 수정되었습니다)
- hour 관련하여 padWithzero 처리 추가합니다.
- 시간 관련 revalidate 로직 삭제합니다.
- wil,week 소문자로 변경
=> [Feat] 수강신청 페이지 큐에이 반영

apps/admin/components/Navbar.tsx, apps/admin/constants/router/routerPath.ts
- 네비게이션 관련 QA 이슈들을 해결합니다.
- https://www.notion.so/QA-a65d59c998d949d791dca2f2474267b3?pvs=4
- https://www.notion.so/QA-313c9acf6017496580da95fe1d246290?pvs=4
=> [Fix] 네비게이션 관련 QA 이슈 해결

apps/admin/app/layout.tsx, apps/admin/app/studies/[studyId]/_components/assignment/AssignmentButtons.tsx, apps/admin/app/studies/[studyId]/_components/assignment/AssignmentList.tsx, apps/admin/app/studies/[studyId]/_components/assignment/AssignmentListItem.tsx, apps/admin/app/studies/[studyId]/_components/curriculum/CurriculumListItem.tsx, apps/admin/app/studies/assignments/[studyDetailId]/_components/AssignmentForm.tsx, apps/admin/app/studies/assignments/[studyDetailId]/edit-assignment/page.tsx, apps/admin/app/studies/assignments/[studyDetailId]/page.tsx, apps/admin/types/dtos/assignmentList.ts, apps/admin/utils/getIsCurrentWeek.ts, package.json, packages/utils/src/formatDate.ts, pnpm-lock.yaml
- 기존에 하드코딩으로 넣어주었던 과제 마감일을 Picker 컴포넌트로 선택할 수 있도록 합니다.
- 폼을 모두 작성하지 않아도 버튼이 활성화되었던 문제를 해결합니다.
- 과제 휴강 후 상태가 반영되도록 합니다.
- 현재 week인지 판단하는 로직을 수정합니다.
- #75 
- https://www.notion.so/QA-b4a9d46b86574e818f68360dbcbbde26?pvs=4
- `parseISODate`가 우리나라 기준이 아니어서 백엔드 응답과 9시간 차이가 나는 부분을 수정했습니다.
- 과제가 아직 생성되지 않는 경우, `null`로 오는 필드들이 있어서 DTO 수정했습니다.
=> [Feature] 과제 Picker 컴포넌트 도입 및 QA사항 반영

apps/client/app/(afterLogin)/my-study/@modal/(.)attendance-check/page.tsx, apps/client/app/(afterLogin)/my-study/_components/AttendanceStatusBox.tsx, apps/client/app/(afterLogin)/my-study/_components/DailyTasks.tsx, apps/client/app/(afterLogin)/my-study/_components/StudyAnnouncementList.tsx, apps/client/app/(afterLogin)/my-study/_components/StudyCurriculum.tsx, apps/client/hooks/useFetchAttendanceCheckModalInfoData.ts
나의 스터디 페이지 QA 반영했습니다.
- 출석체크 모달 하드 코딩된 부분 수정
- 출석체크 시 studyId 대신 studyDetailId로 수정
- 출석체크 완료 이후 버튼 disabled로 처리
- 출석체크 모달 버튼 maxWidth 설정
- 스터디 커리큘럼 휴강주차 표시
- 스터디 공지 UI 깨짐 이슈 해결
- 오늘의 할 일 및 스터디 공지가 없을 때 UI 반영
- 스터디 커리큘럼 태그 UI 다른 부분 수정
- #115 
스터디 커리큘럼 상세 정보가 없는 경우 UI 부분은 디자인에 반영해주시면 다음 PR에서 반영해두겠습니다!
=> [Chore] 나의 스터디 페이지 QA 반영

apps/admin/app/studies/[studyId]/_components/assignment/AssignmentListItem.tsx, apps/admin/app/studies/[studyId]/_components/attendance/AttendanceItem.tsx, apps/admin/app/studies/[studyId]/_components/curriculum/CurriculumListItem.tsx, apps/admin/app/studies/assignments/[studyDetailId]/_components/AssignmentHeader.tsx, apps/admin/utils/getIsToday.ts
- [과제 리스트 간격 UI](https://www.notion.so/QA-UI-fa1aa1d8de254498be0967fc6bc72e5b?pvs=4)
- [출결번호 진행중 상태](https://www.notion.so/QA-6594e74b5eed456b88d18ec430792565?pvs=4)
- [주차별 과제 정렬](https://www.notion.so/QA-UI-4126e33009e44fc1b57f92fe08410f88?pvs=4)
- [과제 종료기한 두줄](https://www.notion.so/QA-f91cf810ec3a456ab228e0cc72e97033?pvs=4)
- [과제 생성/수정 타이틀 누락](https://www.notion.so/QA-3e1c1336e05b488991b5a96f16389244?pvs=4)
- #117
=> [Fix] 과제, 출결 관련 QA 반영

apps/admin/app/studies/[studyId]/@modal/(.)announcement-modify/page.tsx, apps/admin/app/studies/[studyId]/_components/announcement/CreateStudyAnnouncement.tsx, apps/admin/app/studies/[studyId]/_components/curriculum/CurriculumListItem.tsx, apps/admin/app/studies/[studyId]/page.tsx, apps/admin/app/studies/_components/StudyListItem.tsx, apps/admin/app/studies/create-study/_components/StudyBasicInformation/StudyApplyDatePick.tsx, apps/admin/app/studies/create-study/_components/StudyBasicInformation/StudyCourseSelect.tsx, apps/admin/app/studies/create-study/_components/StudyBasicInformation/StudyDayOfWeekSelect.tsx, apps/admin/app/studies/create-study/_components/StudyBasicInformation/StudyFormatSelect.tsx, apps/admin/app/studies/create-study/_components/StudyBasicInformation/StudySemesterSelect.tsx, apps/admin/app/studies/create-study/_components/StudyBasicInformation/StudyStartDatePick.tsx, apps/admin/app/studies/create-study/_components/StudyBasicInformation/StudyTime.tsx, apps/admin/app/studies/create-study/_components/StudyBasicInformation/index.tsx, apps/admin/app/studies/create-study/_components/StudyMentorSelect.tsx, apps/admin/app/studies/create-study/page.tsx, apps/admin/app/studies/detail-info/[studyId]/_components/StudyInfoBox/StudyInfoStatus.tsx, apps/admin/app/studies/detail-info/[studyId]/_hooks/usePrefillStudyDetailInfo.ts, apps/admin/hooks/useResizeTextarea.ts, pnpm-lock.yaml
⚠️ 중요 이슈 [[QA] 스터디 개설시 학년도와 학기 따로 입력 받도록 수정](https://www.notion.so/QA-7b7d98a66ebc46fdaa9fef79210300f3?pvs=4)
⚠️ 중요 이슈 [[QA] 스터디 커리큘럼 OPEN 으로 변경](https://www.notion.so/QA-OPEN-b9f5b7ee014441c5b3b4b764e972af88?pvs=4)
[[QA] 아이콘과 텍스트가 너무 떨어져있어요](https://www.notion.so/QA-72492f91fd0341f18469fdbc63e6ce73?pvs=4)
[[QA] 멘토 검색시 학번도 같이 띄워주세요](https://www.notion.so/QA-1e495b601bf54ff5a0252132eb802802?pvs=4)
[[QA] 스터디 커리큘럼 하단 마진](https://www.notion.so/QA-d9b8a98122de4bd693d020281b3ba3dd?pvs=4)
[[QA] 스터디 휴강 주차 표시 안 됨](https://www.notion.so/QA-f220d6df021e46328fc09e78cfdfdb16?pvs=4)
[[QA] 공지 수정 시 url 짤리는 문제](https://www.notion.so/QA-url-8a701321a7764e9da9df8dd12f77f500?pvs=4)
어제 QA 진행했던 사항 중 위 내용 수정 완료했습니다~ 
패키지 설치 때문에 diff가 좀 크게 잡히네용,,,😅
=> [Fix] 자잘한 UI 수정 및 개설 강의 상태 NONE에서 OPEN으로 변경, QA 반영

apps/admin/app/studies/create-study/_components/StudyBasicInformation/StudyApplyDatePick.tsx, apps/admin/app/studies/create-study/_components/StudyBasicInformation/StudyCourseSelect.tsx, apps/admin/constants/studyCurriculum.ts
혁님이 오늘 오후에 수정 요청주셨던 두 부분 수정 완료하였습니다!
1. 스터디 커리큘럼을 12주까지로 설정할 수 있어요.
2. 스터디 시작 기간 이후에도 스터디를 신청 받을 수 있어요.
#124
=> [Hotfix] 스터디 커리큘럼 12주로 연장, 스터디 신청 기간 자유롭게 선택 가능하도록 수정

apps/client/components/Navbar.tsx, apps/client/constants/navMenu.ts
- 과제 페이지 QA 사항이 반영되지 않아 우선 네비게이션 바에서 제거합니다~
=> [HotFix]: 과제 페이지 롤백

apps/admin/app/studies/create-study/_components/StudyBasicInformation/StudyStartDatePick.tsx
스터디 신청 기간에만 disabled list를 반영해두었는데, 스터디 진행 기간에도 disabled list를 설정해야하여 반영해둡니다!
=> [Hotfix] 스터디 신청 기간 날짜 겹치지 않도록 수정

apps/admin/app/students/page.tsx
어드민일때만 수강생 목록이 보여지는 이슈를 해결합니다.
=> [Fix] 수강생 목록 어드민일때만 보여지는 이슈 수정

apps/admin/utils/revalidateTagByName.ts, apps/client/app/(afterLogin)/my-study/my-assignment/_components/AssignmentContent/AssignmentOverviewBox/AssignmentBoxButtons.tsx, apps/client/app/(afterLogin)/my-study/my-assignment/_components/AssignmentContent/AssignmentOverviewBox/index.tsx, apps/client/app/(afterLogin)/my-study/my-assignment/_components/AssignmentContent/RepositorySubmissionBox.tsx, apps/client/app/(afterLogin)/study-apply/@modal/(.)study-application/[studyId]/page.tsx, apps/client/app/(afterLogin)/study-apply/@modal/(.)study-cancellation/[studyId]/page.tsx, apps/client/app/(afterLogin)/study-apply/_components/EmptyStudyApplication.tsx, apps/client/app/(afterLogin)/study-apply/page.tsx, apps/client/utils/revalidateTagByName.ts
- 과제 제출했을 때 제출 이후의 assignment 상태를 반영하여 toast 띄우기
- 수강 가능한 스터디 없을 때 Empty 컴포넌트 추가
=> [Fix] 과제 제출 관련 버그 수정

apps/client/app/(afterLogin)/my-study/_components/DailyTaskItem.tsx, apps/client/types/dtos/myStudy.ts
- 내 할일 api dto 변경에 따라 프론트에도 반영합니다.
- todoType => taslType 으로 변경
https://gdschongik.slack.com/archives/C06PWADQV5Z/p1730291978738939?thread_ts=1730291635.973599&channel=C06PWADQV5Z&message_ts=1730291978.738939
=> [Fix] 내 할일 api dto 변경

apps/client/app/(afterLogin)/my-page/_components/CompletedStudy.tsx
- 마이페이지 테이블 ui 를 수정합니다.
- tr 상위에 div 태그로 인해 테이블의 width 가 full 로 나오지 않는 문제가 있었습니다.
- 상위 div 태그와 불필요한 엘리먼트를 제거합니다.
as-is
to-be
=> [Fix] 마이페이지 table ui 수정

apps/client/app/(afterLogin)/(mobile)/mobile/_components/PageHeader.tsx, apps/client/app/(afterLogin)/(mobile)/mobile/my-study/_components/AttendanceStatusBox.tsx, apps/client/middleware.ts
- auth 페이지에 접근하면 계속 리다이렉트 되는 문제 해결합니다.
- auth 페이지가 미들웨어를 거치도록 수정하면서  AT 가 있는지 확인하고 auth 페이지로 리다이렉트 되는 로직(페이지 가드)이 적용되면서 무한 리다이렉트 되는 이슈였습니다.
- auth  페이지는  가드 가 적용되지 않도록 수정합니다.
- 모바일 auth 페이지에서는 Header 에서 계정 정보를 가져오도록 api fetch 가 이루어지고 있는데 이때 로그인이 되어 있지 않으면 500 에러가 발생합니다.
- auth 페이지에서는 api를 fetch 하지 않도록  pathname 에 대한 정보를 가져와서 분기처리 하도록 합니다.
- 서버 컴포넌트에서 pathname 을 가져올 수 있도록 미들웨어에서 header 에 x-pathname 을 추가하도록 합니다.
=> [Fix] auth 페이지에 접근하면 계속 리다이렉트 되는 문제 해결

apps/admin/apis/study/studyAchievementApi.ts, apps/admin/apis/study/studyCompleteApi.ts, apps/admin/app/students/_components/StudentTable/StudyTasks.tsx
스터디 수료, 우수회원 처리 API를 v2 버전으로 변경하였습니다.
요청 처리 URL만 변경하면 되는 간단한 작업이었기 때문에 빠르게 업로드합니다!
=> [Feature] 스터디 수료, 우수회원 처리 v2 api로 변경 

README.md, apps/admin/app/layout.tsx, apps/client/app/(afterLogin)/(pc)/my-study/my-assignment/_components/AssignmentContent/AssignmentOverviewBox/FailurePopover.tsx, apps/client/app/(afterLogin)/(pc)/study-apply/@modal/(.)study-application/[studyId]/page.tsx, apps/client/app/(beforeLogin)/(auth-error)/auth-error-after-recruitment/page.tsx, apps/client/app/(beforeLogin)/(auth-error)/auth-error-during-recruitment/page.tsx, apps/client/app/(beforeLogin)/auth/page.tsx, apps/client/app/(beforeLogin)/landing/page.tsx, apps/client/app/(beforeLogin)/social-login/redirect/page.tsx, apps/client/app/layout.tsx, apps/client/middleware.ts, packages/ui/src/components/Header/index.tsx
=> [Fix] 학생용 페이지 관련 QA

apps/client/middleware.ts
=> [Fix] 미들웨어 주석 추가

apps/admin/app/studies/detail-info/[studyId]/_components/AssignmentInfoBox/AssignmentDatePick.tsx, apps/admin/app/studies/detail-info/[studyId]/_components/AssignmentInfoBox/index.tsx, apps/admin/app/studies/detail-info/[studyId]/_components/StudyInfoBox/StudyDatePick.tsx, apps/admin/app/studies/detail-info/[studyId]/_components/StudyInfoBox/index.tsx
=> [Feat] 캘린더 따닥 이슈 해결

apps/admin/app/studies/detail-info/[studyId]/_components/AssignmentInfoBox/AssignmentTextInfo.tsx, apps/admin/app/studies/detail-info/[studyId]/_components/StudyInfoBox/StudyTextInfo.tsx, apps/admin/app/studies/detail-info/[studyId]/_hooks/usePrefillStudyDetailInfo.ts, apps/admin/types/dtos/studyDetailInfo.ts, apps/admin/types/dtos/studyList.ts, apps/admin/utils/validate/studyDetailInfo.ts
- title -> lessonTitle 로 변경
- assignmentTitle 추가
=> [Fix] studySession title 관련 dto 수정된 부분 반영합니다.

apps/client/app/(afterLogin)/(pc)/study-apply/_components/StudyItem.tsx
=> [Feat] 취소 버튼 서브 컬러로 변경

apps/admin/app/studies/_components/StudyList.tsx
=> [Fix] hook 순서 수정

apps/admin/app/studies/_components/StudyList.tsx, apps/client/app/(afterLogin)/(pc)/study-apply/_components/StudyItem.tsx
=> [FIx] 어드민 터지는 문제 수정

apps/admin/app/studies/_components/StudyList.tsx, apps/client/app/(afterLogin)/(pc)/study-apply/_components/StudyItem.tsx, apps/client/utils/isValidDate.ts
=> [Fix] 타임 로직 테스트

apps/client/utils/isValidDate.ts
=> [Fix] kst 로 수정

apps/admin/app/studies/_components/StudyList.tsx, apps/client/app/(afterLogin)/(pc)/study-apply/_components/StudyItem.tsx, apps/client/utils/isValidDate.ts
=> [Fix] 테스트 코드 삭제

package.json, pnpm-lock.yaml
=> [Feat] 와디 최신으로 버전업

apps/client/app/(afterLogin)/(pc)/my-study/[studyId]/_components/StudyCurriculum/CurriculumItem.tsx
=> [Fix] 출석 태그 아닌 과제 상태 태그로 변경

apps/client/apis/studyHistoryApi.ts, apps/client/app/(afterLogin)/(pc)/my-page/_components/CompletedStudy.tsx, apps/client/app/(afterLogin)/(pc)/my-study/[studyId]/_components/StudyCurriculum/CurriculumItem.tsx, apps/client/types/dtos/studyHistory.ts
=> [Fix] 마이페이지 수료내역 v2

apps/client/app/(afterLogin)/(pc)/my-page/page.tsx
=> [HotFix]: 수료내역 제외

apps/client/app/(afterLogin)/(pc)/my-page/_components/CompletedStudy.tsx
- 서버 컴포넌트로 처리했을 떄 아래와 같은 에러뜸
```
Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```
- hotfix 를 위해 수료 컴포넌트 클라이언트 컴포넌트로 처리 합니다.
=> [Hotfix] 수료 컴포넌트 클라이언트 컴포넌트로 처리

apps/client/app/(afterLogin)/(pc)/my-page/page.tsx
=> [Fix] 수료내역 컴포넌트로 추가

.github/CODEOWNERS, apps/admin/app/studies/[studyId]/_components/attendance/AttendanceItem.tsx, apps/admin/constants/status/attendanceStatusMap.ts, apps/admin/utils/geIsAfterDate.ts, apps/client/apis/myStudyApi.ts, apps/client/apis/studyDetailApi.ts, apps/client/app/(afterLogin)/(pc)/my-study/_components/MyOngoingStudy.tsx, apps/client/components/Navbar.tsx
- 멘토용 페이지에서 출석 관련 태그에 완료 태그 추가
- 학생용 페이지에서 공지, basic info 관련 api cache 처리하도록 수정
- 네비게이션 바도 ongoing api 사용하도록 수정
- overflow 관련 디자인 수정
=> [Fix] 학생용 페이지, 멘토용 페이지 디자인 수정 및 api 수정

apps/admin/constants/status/attendanceStatusMap.ts
- 출석 태그의 제출 완료 태그 컬러를 grey 로 변경
=> [Fix] 출석 태그 color grey 로 변경

apps/admin/constants/status/attendanceStatusMap.ts, apps/client/app/(afterLogin)/(pc)/my-study/[studyId]/_components/StudyCurriculum/CurriculumItem.tsx
- 과제 스터디 의 경우에는 회차 날짜가 나오지 않도록 수정합니다.
- https://gdgochongik.slack.com/archives/C06PWADQV5Z/p1743059332086179?thread_ts=1743040981.997409&channel=C06PWADQV5Z&message_ts=1743059332.086179
=> [Fix] 과제 스터디 의 경우에는 회차 날짜가 나오지 않도록 수정

apps/client/app/(afterLogin)/(pc)/my-study/[studyId]/_components/StudyCurriculum/CurriculumItem.tsx
- https://github.com/GDSC-Hongik/wow-class/pull/218 에서 반영되지 않은 디자인 수정 반영합니다.
=> [Fix] 디자인 수정

apps/admin/constants/status/attendanceStatusMap.ts
=> [Deploy] 과제 스터디 일 때 회차 정보 안보이게 수정

apps/admin/app/studies/[studyId]/_components/curriculum/CurriculumListItem.tsx, apps/admin/app/studies/[studyId]/_components/statics/StudyAnalyticsGraph.tsx, apps/admin/app/studies/[studyId]/_components/statics/StudyStatics.tsx
- 과제 스터디 인 경우에는 회차 날짜도 나오지 않게 분기처리에 추가합니다.
=> [Fix] 과제 스터디 인 경우에는 회차 날짜도 나오지 않게 수정

apps/admin/app/studies/[studyId]/_components/curriculum/CurriculumListItem.tsx
=> [Fix]  불필요한 텍스트 수정

apps/admin/app/studies/[studyId]/_components/curriculum/CurriculumListItem.tsx, apps/admin/app/studies/[studyId]/_components/statics/StudyAnalyticsGraph.tsx, apps/admin/app/studies/[studyId]/_components/statics/StudyStatics.tsx
=> [Deploy] 멘토용 페이지 디자인 수정 배포

apps/admin/constants/studyCurriculum.ts
=> [Deploy] 커리쿨럼 15주차까지 생성 배포 (#233)

.github/CODEOWNERS, apps/admin/app/layout.tsx, apps/admin/app/students/layout.tsx, apps/admin/app/studies/[studyId]/_components/curriculum/CurriculumList.tsx, apps/admin/app/studies/[studyId]/_components/curriculum/CurriculumListItem.tsx, apps/admin/app/studies/[studyId]/page.tsx, apps/admin/app/studies/layout.tsx, apps/admin/components/Navbar.tsx, apps/admin/utils/isOnlineOfflineStudyType.ts, apps/client/app/(afterLogin)/(pc)/my-page/layout.tsx, apps/client/app/(afterLogin)/(pc)/my-study/[studyId]/_components/StudyCurriculum/CurriculumItem.tsx, apps/client/app/(afterLogin)/(pc)/my-study/layout.tsx, apps/client/app/(afterLogin)/(pc)/study-apply/layout.tsx, apps/client/utils/isOnlineOfflineStudyType.ts, package.json, packages/ui/src/components/NavItem/index.tsx
=> [Deploy] 자잘한 버그 수정 배포

apps/admin/app/studies/create-study/_components/StudyBasicInformation/WilMinimumLength.tsx, apps/admin/app/studies/create-study/_components/StudyBasicInformation/index.tsx, apps/admin/app/studies/detail-info/[studyId]/_hooks/useSubmitStudyDetailInfo.ts, apps/admin/types/dtos/createStudy.ts, apps/admin/types/dtos/studyBasicInfo.ts, apps/admin/types/dtos/studyList.ts, apps/client/app/(afterLogin)/(pc)/my-study/_components/MyOngoingStudy.tsx, apps/client/app/(afterLogin)/(pc)/my-study/_components/common/DailyTask/AssignmentOverviewBox/AssignmentBoxInfo.tsx, apps/client/app/(afterLogin)/(pc)/my-study/_components/common/DailyTask/AssignmentOverviewBox/FailurePopover.tsx, apps/client/types/dtos/myStudy.ts, apps/client/types/dtos/studyDetail.ts
=> [Deploy] 최소 글자수 제한 추가 (#237)

apps/admin/app/studies/detail-info/[studyId]/_hooks/usePrefillStudyDetailInfo.ts, apps/admin/app/studies/detail-info/[studyId]/page.tsx, apps/admin/types/dtos/studyDetailInfo.ts
=> [Deploy] minLength prefill 로 들어가도록 수정 (#239)

apps/admin/types/dtos/auth.ts, apps/client/types/dtos/auth.ts
=> [Feat] 3차 모집 반영

apps/admin/types/dtos/auth.ts, apps/client/types/dtos/auth.ts
Reverts gdg-hongik-univ/wow-class#246
=> Revert "[Feat] 3차 모집 반영"

pnpm-lock.yaml
=> [Fix] Sentry 추가 후 pnpm lock 파일 업데이트
